name: Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: ['v*']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: test-deploy

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test-deploys:$(date +%s)

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}