name: Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: ['v*']
  schedule:
    - cron: '10 6 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: test-deploy
        # Trigger on merge to main, nightly, PR to main, and manual trigger
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=schedule,pattern=nightly
          type=semver,pattern={{major}}.{{minor}}.{{patch}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5
      with:
        github-token: ${{ secrets.github_token }}
        output-file: "false"

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}