name: Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: ['v*']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: test

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test-deploys:$(date +%s)

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
          type=ref,event=tag
          type=schedule,pattern=nightly
          type=semver,pattern={{major}}.{{minor}}.{{patch}}